image: debian:buster

test:
  before_script:
    - apt update -qq
    - apt install -qq -y --no-install-recommends git gcc make autoconf automake libtool
  script:
    - ./autogen && ./configure
    - make check
